export const sampleTables = [
  {
    id: 1,
    tableNumber: 'T1',
    seats: 4,
    status: 'Available',
  },
  {
    id: 2,
    tableNumber: 'T2',
    seats: 6,
    status: 'Occupied',
    customerName: 'John',
    customerCount: 4,
    occupiedSince: '6:45 PM',
  },
  {
    id: 3,
    tableNumber: 'T3',
    seats: 2,
    status: 'Reserved',
    customerName: 'Sarah',
    customerCount: 2,
    reservationDate: 'Today',
    reservationTime: '7:30 PM',
  },
  {
    id: 4,
    tableNumber: 'T4',
    seats: 4,
    status: 'Available',
  },
  {
    id: 5,
    tableNumber: 'T5',
    seats: 4,
    status: 'Occupied',
    customerName: 'David',
    customerCount: 3,
    occupiedSince: '7:15 PM',
  },
  {
    id: 6,
    tableNumber: 'T6',
    seats: 2,
    status: 'Available',
  },
  {
    id: 7,
    tableNumber: 'T7',
    seats: 8,
    status: 'Occupied',
    customerName: 'Emily',
    customerCount: 5,
    occupiedSince: '6:30 PM',
  },
  {
    id: 8,
    tableNumber: 'T8',
    seats: 4,
    status: 'Reserved',
    customerName: 'Michael',
    customerCount: 4,
    reservationDate: 'Today',
    reservationTime: '8:00 PM',
  },
  {
    id: 9,
    tableNumber: 'T9',
    seats: 6,
    status: 'Available',
  },
  {
    id: 10,
    tableNumber: 'T10',
    seats: 2,
    status: 'Occupied',
    customerName: 'Jessica',
    customerCount: 2,
    occupiedSince: '7:00 PM',
  },
  {
    id: 11,
    tableNumber: 'T11',
    seats: 6,
    status: 'Reserved',
    customerName: 'Alex',
    customerCount: 6,
    reservationDate: 'Today',
    reservationTime: '8:30 PM',
  },
  {
    id: 12,
    tableNumber: 'T12',
    seats: 4,
    status: 'Available',
  },
  {
    id: 13,
    tableNumber: 'T13',
    seats: 2,
    status: 'Available',
  },
  {
    id: 14,
    tableNumber: 'T14',
    seats: 4,
    status: 'Occupied',
    customerName: 'Robert',
    customerCount: 4,
    occupiedSince: '7:20 PM',
  },
  {
    id: 15,
    tableNumber: 'T15',
    seats: 2,
    status: 'Reserved',
    customerName: 'Amanda',
    customerCount: 2,
    reservationDate: 'Tomorrow',
    reservationTime: '6:00 PM',
  },
];
